description: >
  tfsec container executor
docker:
  - image: "tfsec/tfsec-ci:<<parameters.tag>>"
    user: root
parameters:
  tag:
    default: latest
    description: >
      Pick a specific tfsec/tfsec-ci image tag:
      https://hub.docker.com/r/tfsec/tfsec-ci/tags
    type: string
