description: >
  tfsec container executor
docker:
  - image: "tfsec/tfsec:<<parameters.tag>>"
parameters:
  tag:
    default: latest
    description: >
      Pick a specific tfsec/tfsec image tag:
      https://hub.docker.com/r/tfsec/tfsec/tags
    type: string
